syntax = "proto3";

package weather;

option java_multiple_files = true;
option java_package = "org.ifgoiano.grpc.weather";
option java_outer_classname = "WeatherProto";

message Empty {}

message CidadeRequest {
    string nome = 1;
}

message TemperaturaResponse {
    string cidade = 1;
    double temperatura = 2;
}

message PrevisaoDia {
    string data = 1;
    double temperatura = 2;
}

message PrevisaoResponse {
    string cidade = 1;
    repeated PrevisaoDia dias = 2;
}

message CidadesResponse {
    repeated string cidades = 1;
}

message CadastrarCidadeRequest {
    string nome = 1;
}

message CadastrarCidadeResponse {
    bool sucesso = 1;
    string mensagem = 2;
}

message EstatisticasResponse {
    string cidade = 1;
    double media_temperatura = 2;
    double minima = 3;
    double maxima = 4;
}

service WeatherService {
    rpc ObterTemperaturaAtual (CidadeRequest) returns (TemperaturaResponse);
    rpc PrevisaoCincoDias (CidadeRequest) returns (PrevisaoResponse);
    rpc ListarCidades (Empty) returns (CidadesResponse);
    rpc CadastrarCidade (CadastrarCidadeRequest) returns (CadastrarCidadeResponse);
    rpc EstatisticasClimaticas (CidadeRequest) returns (EstatisticasResponse);
}
