spring.application.name=grpc-weather

# gRPC Server
grpc.server.port=9090

# gRPC Client
grpc.client.weatherService.address=static://127.0.0.1:9090
grpc.client.weatherService.negotiationType=plaintext

# HTTP Server
server.port=8080
